GET http://localhost:5017/games

###
GET http://localhost:5017/games/1

###
POST http://localhost:5017/games
Content-Type: application/json

{
    "name": "Juego",
    "genreId": 3,
    "price": 59.90,
    "releaseDate": "2023-10-20"
}

###
PUT http://localhost:5017/games/1
Content-Type: application/json

{
    "id": 1,
    "name": "Street Figther II 123 122",
    "genreId": 4,
    "price": 19.99,
    "releaseDate": "1992-07-15"
}

###
DELETE http://localhost:5017/games/2



###
GET http://localhost:5017/genres